version: 0.1
phases:
  build:
    commands:
      - ./gradlew build
artifacts:
  files:
      - dist/**/*
      - awsscripts/install_dependencies.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml   
discard-paths: yes
