version: 0.1
phases:
  build:
    commands:
      - cd fineract-provider
      - ./gradlew dist
      - ls -al
artifacts:
  files:
      - build/libs/*
      - awsscripts/install_dependencies.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml   
discard-paths: yes
